### ISSUE TITLE
Code use in one of my projects

### ISSUE THREAD

**Issue by fourcube** [djotanov/undertow-jsp-template#1]
First of all: Thanks for the work you put into this! It saved me a lot of time.

I just wanted to let you know, that I've copied your code which enumerates and loads all `taglibs`. I've added a link to your repository as a comment in the respective source file.

https://github.com/fourcube/undertow-jsp-sample/blob/master/src/main/java/com/grieger/sample/undertow/TldLocator.java

**Comment by djotanov** [comment]
Hey, nice to know that someone could find it useful.
Cheers
